// Todos los textos visibles de EDAVI Studio, en un único lugar.
// Para cambiar un mensaje o traducir la app, edita solo este archivo.
// Las funciones reciben los valores variables (nombres, cantidades…).
import { BRAND } from './brand.js';

const plural = (n, one, many) => `${n} ${n === 1 ? one : many}`;

export const COPY = {
  studios: {
    explore: { label: 'Explorar', blurb: 'Todos tus modelos y creaciones en un vistazo.' },
    image: { label: 'Imagen', blurb: 'Retratos, producto, carteles y edición con referencias.' },
    video: { label: 'Video', blurb: 'Texto, imagen o referencias a video, con audio nativo.' },
    transform: { label: 'Transformar', blurb: 'Edita, extiende o transfiere movimiento a un video existente.' },
    characters: { label: 'Personajes', blurb: 'Crea tu avatar con Soul ID y úsalo en los modelos SOUL.' },
    prompts: { label: 'Prompts', blurb: 'Más de 1.500 prompts listos para usar.' },
    library: { label: 'Biblioteca', blurb: 'Todas tus creaciones, con filtros y acciones en lote.' },
  },

  app: {
    skip: 'Saltar al contenido',
    home: `${BRAND.name}: inicio`,
    demo: 'DEMO',
    spentToday: (cr) => `≈ ${cr} cr hoy`,
    spentTodayHint: 'Estimación de créditos usados hoy en este navegador',
    create: 'Crear',
    settings: 'Ajustes',
    more: 'Más',
    moreTitle: 'Más opciones',
    navLabel: 'Estudios',
    mobileNavLabel: 'Navegación principal',
    running: (n) => `${n} en proceso`,
    themeToDark: 'Cambiar a modo oscuro',
    themeToLight: 'Cambiar a modo claro',
    themeDark: 'Modo oscuro',
    themeLight: 'Modo claro',
    themeHint: 'Cambia entre morado y blanco con dorado.',
    settingsHint: 'Tu clave de Higgsfield y el estado del servidor.',
    footer: { by: 'Creado por', license: 'Código abierto · MIT', powered: 'Funciona con la API de Higgsfield' },
    notices: {
      login: ['Inicia sesión para crear.', 'Tu historial y tus archivos se guardan en tu nube y los ves desde cualquier dispositivo.'],
      key: ['Conecta Higgsfield para empezar.', 'Añade tu clave (KEY_ID:KEY_SECRET) en Ajustes o configura las credenciales en el servidor.'],
      offline: 'Sin conexión. Tus generaciones siguen en cola y se reanudan al volver la red.',
    },
  },

  account: {
    signIn: 'Entrar',
    menu: 'Tu cuenta',
    signedInAs: 'Sesión iniciada como',
    signOut: 'Cerrar sesión',
    library: 'Mi biblioteca',
    replayOnboarding: 'Ver la bienvenida',
  },

  auth: {
    titles: { signin: 'Entrar', signup: 'Crear cuenta', reset: 'Recuperar acceso', recovery: 'Nueva contraseña' },
    lead: {
      signin: `Inicia sesión para generar y guardar tu historial en la nube de ${BRAND.name}.`,
      signup: 'Crea tu cuenta para guardar tus creaciones y usar el estudio desde cualquier dispositivo.',
      reset: 'Te enviaremos un enlace para crear una contraseña nueva.',
      recovery: 'Elige una contraseña nueva para tu cuenta.',
    },
    email: 'Email',
    password: 'Contraseña',
    passwordHint: 'Mínimo 8 caracteres.',
    showPassword: 'Mostrar contraseña',
    hidePassword: 'Ocultar contraseña',
    submit: { signin: 'Entrar', signup: 'Crear cuenta', reset: 'Enviar enlace', recovery: 'Guardar contraseña' },
    busy: { signin: 'Entrando…', signup: 'Creando…', reset: 'Enviando…', recovery: 'Guardando…' },
    newPassword: 'Contraseña nueva',
    toSignup: '¿No tienes cuenta? Crear una',
    toSignin: '¿Ya tienes cuenta? Entrar',
    toReset: '¿Olvidaste la contraseña?',
    back: 'Volver a entrar',
    close: 'Cerrar',
    done: {
      signup: 'Revisa tu email para confirmar la cuenta y después entra.',
      reset: 'Si el email existe, te llegará un enlace en unos minutos.',
      recovery: 'Contraseña actualizada. Ya puedes crear.',
      welcome: '¡Cuenta creada! Ya puedes crear.',
    },
    errors: {
      invalid: 'Email o contraseña incorrectos.',
      weak: 'La contraseña debe tener al menos 8 caracteres.',
      email: 'Escribe un email válido.',
      generic: 'No se pudo completar. Inténtalo de nuevo.',
      rate: 'Demasiados intentos. Espera un minuto.',
    },
    required: 'Inicia sesión para generar.',
  },

  onboarding: {
    label: 'Bienvenida',
    skip: 'Saltar',
    next: 'Siguiente',
    back: 'Atrás',
    finish: 'Empezar a crear',
    step: (i, n) => `Paso ${i} de ${n}`,
    steps: [
      {
        title: `Hola, soy EDAVI`,
        text: 'Tu estudio creativo con los mejores modelos de imagen y video de Higgsfield. Te enseño lo básico en 3 pasos.',
      },
      {
        title: '¿Qué quieres crear primero?',
        text: 'Elige un punto de partida. Puedes cambiarlo cuando quieras desde el menú.',
        choices: [
          { id: 'image', label: 'Imágenes', hint: 'Retratos, producto, carteles' },
          { id: 'video', label: 'Videos', hint: 'Clips con audio nativo' },
          { id: 'prompts', label: 'Inspirarme', hint: 'Más de 1.500 prompts' },
        ],
      },
      {
        title: 'Elige tu estilo',
        text: 'Oscuro morado o claro con dorado. Tu elección se recuerda en este dispositivo.',
      },
    ],
  },

  explore: {
    eyebrow: 'Estudio creativo con IA · Higgsfield',
    hero: ['Imagina cualquier cosa.', 'Créala en segundos.', 'Imagen y video de cine.'],
    sub: (n) => `${n} modelos de IA en un solo estudio: SOUL, Seedance, Kling, Wan, MiniMax y más. Con biblioteca de prompts, comparación de modelos, flujos automáticos y tu propio avatar.`,
    ctaPrimary: 'Empezar a crear',
    ctaPrompts: (n) => `Ver ${n} prompts`,
    stats: { models: 'Modelos', prompts: 'Prompts', video: 'Video', variations: 'Variaciones' },
    featured: ['Destacados', 'Los modelos más potentes para empezar.'],
    all: 'Todos los modelos',
    filters: { all: 'Todos', image: 'Imagen', video: 'Video', transform: 'Transformar' },
    showAll: (n) => `Ver los ${n} modelos`,
    showLess: 'Ver menos',
    creations: ['Tus creaciones', 'Lo que generes aparece aquí.'],
    seeLibrary: 'Abrir biblioteca',
    emptyCreations: 'Tu galería está vacía',
    emptyCta: 'Crear mi primer video',
    kinds: { image: 'Imagen', video: 'Video', transform: 'Transformar' },
    bannersLabel: 'Destacados',
    banners: [
      { over: 'Nuevo en EDAVI', lines: ['SEEDANCE', '2.5'], sub: 'Video con audio nativo', title: 'Seedance 2.5', text: 'Genera, edita y extiende video hasta 30 s con referencias.' },
      { over: 'Retrato · Moda · Editorial', lines: ['SOUL', 'V2'], sub: 'Estilos de revista', title: 'SOUL V2', text: 'Retratos editoriales con estilos y tu propio avatar.' },
      { over: 'Motion control', lines: ['MUEVE', 'TU FOTO'], sub: 'Kling 3.0', title: 'Kling 3.0 Motion Control', text: 'Copia el movimiento de un video a cualquier imagen.' },
      { over: 'Dirección de fotografía', lines: ['CINEMA', 'STUDIO 4'], sub: 'Cámara · Lente · Luz', title: 'Cinema Studio 4.0', text: 'Planos de cine con control total de cámara y época.' },
    ],
  },

  composer: {
    label: 'Compositor',
    modes: 'Modo',
    model: 'Modelo',
    chooseModel: 'Elige un modelo',
    families: (n) => `${n} familias`,
    modesCount: (n) => (n > 1 ? `${n} modos` : '1 modo'),
    close: 'Cerrar',
    library: 'Biblioteca',
    quantity: 'Cantidad',
    less: 'Menos',
    more: 'Más',
    advanced: 'Configuración avanzada',
    animate: ['Animar al terminar', 'La imagen se convierte en video automáticamente.'],
    animateModel: 'Modelo de video',
    animatePlaceholder: 'Movimiento: la cámara orbita lentamente, el pelo se mueve con el viento…',
    animateError: (msg) => `Animación: ${msg}`,
    compare: 'Comparar con otros modelos',
    compareCount: (chosen, total) => (chosen ? `${chosen}/3` : `${total} compatibles`),
    notes: 'Notas del modelo',
    docs: 'docs ↗',
    cost: {
      incomplete: 'Completa los campos obligatorios',
      loading: 'Calculando costo…',
      unavailable: 'Costo no disponible',
      value: (credits, usd, partial) => `≈ ${credits} créditos · $${usd}${partial ? '+' : ''}`,
      hint: 'Estimación de Higgsfield antes de generar',
    },
    generate: 'Generar',
    generateN: (n) => `Generar ${n}`,
    uploading: 'Subiendo…',
    sent: '¡Enviado!',
    draftRestored: 'Recuperamos tu último borrador.',
    variationLabel: (i, n) => `Variación ${i}/${n}`,
    compareLabel: 'Comparación',
    flowLabel: 'Flujo · animado',
    clearDraft: 'Empezar de cero',
  },

  fields: {
    required: 'Obligatorio',
    promptPlaceholder: 'Describe la escena: sujeto, acción, luz, cámara, atmósfera…',
    negativePlaceholder: 'Lo que NO quieres ver…',
    tagsPlaceholder: '123456, 789012',
    unset: '— Sin especificar —',
    seedEmpty: 'vacío = aleatoria',
    seedPlaceholder: 'Aleatoria',
    seedRandom: 'Semilla al azar',
    colors: (n) => (n ? `${n} colores` : 'opcional'),
    removeColor: 'Quitar color',
    addColor: '+ color',
    choose: 'Elegir',
    remove: 'Quitar',
    shots: (n, max, total) => `${n}/${max} · ${total}s en total`,
    shotPlaceholder: (i) => `Plano ${i}…`,
    shotDuration: 'Duración (s)',
    removeShot: 'Quitar toma',
    addShot: '+ Añadir toma',
    pasteUrl: 'pegar URL',
    uploadFile: 'subir archivo',
    upload: (noun) => `Subir ${noun}`,
    upTo: (n) => `Hasta ${n} · `,
    optional: 'Opcional',
    uploadingPct: (p) => `Subiendo ${p}%`,
    tooMany: (max, ignored) => `Máximo ${max}; se ignoraron ${ignored}.`,
    nouns: { image: ['imagen', 'imágenes'], video: ['video', 'videos'], audio: ['audio', 'audios'] },
    styles: 'ver estilos',
    closeStyles: 'cerrar',
    defaultStyle: 'Estilo por defecto',
    noStyle: 'Sin estilo',
    searchPreset: 'Buscar preset…',
    removePreset: 'Quitar preset ×',
    none: '— Ninguno —',
    createCharacter: (v) => `Crea uno en el estudio «Personajes» (${v || 'SOUL'}).`,
    audio: 'audio',
  },

  gallery: {
    label: 'Resultados',
    history: 'Historial',
    how: 'Cómo funciona',
    search: 'Buscar…',
    searchLabel: 'Buscar en el historial',
    filters: 'Filtros',
    thisStudio: 'Este estudio',
    all: 'Todo',
    favorites: 'Favoritos',
    clear: 'Limpiar',
    clearConfirm: '¿Quitar del historial los resultados terminados? Los favoritos se conservan.',
    emptyTitle: 'Aún no hay nada aquí',
    emptyText: 'Escribe un prompt y pulsa Generar. Tus resultados aparecerán aquí.',
    emptySearch: 'Nada coincide con tu búsqueda.',
    waiting: 'esperando turno',
    generating: 'generando',
    noDetails: 'Sin detalles.',
    noCharge: 'No se cobran créditos.',
    flowLaunched: 'Animación lanzada',
    flowPending: 'Se animará al terminar',
    inCloud: 'En tu nube',
    credits: (cr) => `≈ ${cr} cr`,
    expired: 'Higgsfield conserva los archivos al menos 7 días; puede que ya no estén.',
    cancel: 'Cancelar',
    cannotCancel: 'Ya empezó a procesarse; no se puede cancelar.',
    download: 'Descargar',
    animate: 'Animar →',
    animateHint: 'Animar esta imagen',
    transform: 'Transformar →',
    transformHint: 'Transformar este video',
    save: 'Guardar',
    saving: 'Guardando…',
    saveHint: 'Los archivos de Higgsfield caducan a los 7 días',
    reuse: 'Reusar',
    remove: 'Eliminar del historial',
    favAdd: 'Marcar como favorito',
    favRemove: 'Quitar de favoritos',
    zoom: 'Vista ampliada',
    openOriginal: 'abrir original ↗',
    closeZoom: 'cerrar ×',
    howSteps: {
      image: { title: 'Convierte ideas en imágenes', sub: 'Retratos, producto y carteles con los mejores modelos de imagen.', steps: [['Elige un modelo', 'SOUL para retratos y moda, Recraft para gráficos, Marketing Studio para producto.'], ['Describe o sube referencias', 'Escribe tu idea o sube imágenes para editarlas y combinarlas.'], ['Genera y compara', 'Hasta 4 variaciones y el mismo prompt en varios modelos a la vez.']] },
      video: { title: 'Convierte texto en video', sub: 'Clips cinematográficos con audio nativo, listos para tus proyectos.', steps: [['Escribe o anima', 'Parte de un prompt, de una imagen o de varias referencias.'], ['Dirige la toma', 'Formato, duración, resolución, cámara y audio, según el modelo.'], ['Genera y guarda', 'Mira el costo antes de generar y guarda los mejores en tu nube.']] },
      transform: { title: 'Transforma cualquier video', sub: 'Edita, extiende o copia el movimiento de un video a tu imagen.', steps: [['Sube tu video', 'MP4 de al menos 4 segundos para transferir movimiento.'], ['Añade el cambio', 'Una imagen de personaje, un objeto nuevo o un prompt de edición.'], ['Genera', 'El movimiento original se conserva con el nuevo aspecto.']] },
    },
  },

  library: {
    title: 'Biblioteca',
    sub: (n) => `${plural(n, 'creación', 'creaciones')} en este dispositivo${n ? ' y en tu nube' : ''}.`,
    search: 'Buscar por prompt o modelo…',
    type: { all: 'Todo', image: 'Imágenes', video: 'Videos', favorites: 'Favoritos', failed: 'Con error' },
    sort: { label: 'Ordenar', newest: 'Más recientes', oldest: 'Más antiguas', cost: 'Más costosas' },
    select: 'Seleccionar',
    selectAll: 'Seleccionar todo',
    selected: (n) => `${plural(n, 'seleccionada', 'seleccionadas')}`,
    cancelSelect: 'Listo',
    bulk: { download: 'Descargar', save: 'Guardar en la nube', favorite: 'Favoritas', remove: 'Eliminar' },
    removeConfirm: (n) => `¿Eliminar ${plural(n, 'creación', 'creaciones')} del historial? Los archivos en Higgsfield no se borran.`,
    emptyTitle: 'Tu biblioteca está vacía',
    emptyText: 'Todo lo que generes en Imagen, Video o Transformar se guarda aquí.',
    emptyCta: 'Crear algo ahora',
    openStudio: 'Abrir en su estudio',
    item: (i, n) => `Creación ${i} de ${n}`,
  },

  characters: {
    kicker: 'Entrenamiento',
    title: 'Soul ID',
    lead: 'Entrena un personaje reutilizable a partir de tus fotos. Cuando esté listo, elígelo en «Personaje (Soul ID)» dentro de los modelos SOUL de la misma versión.',
    name: 'Nombre',
    namePlaceholder: 'Ej. Valeria editorial',
    version: 'Versión de SOUL',
    versions: [
      { id: 'v2', label: 'SOUL V2', hint: 'Retratos y moda' },
      { id: 'v1', label: 'SOUL', hint: 'Estilos clásicos' },
      { id: 'cinema', label: 'SOUL Cinema', hint: 'Fotogramas de cine' },
    ],
    photos: 'Fotos del personaje',
    tip: 'Consejo: usa fotos nítidas de la misma persona, con ángulos, luz y expresiones distintas.',
    import: 'Importar un Soul ID existente',
    importPlaceholder: 'ID del personaje (uuid)',
    importCta: 'Importar',
    train: 'Entrenar',
    sending: 'Enviando…',
    cast: 'Reparto',
    castCount: (n) => plural(n, 'personaje', 'personajes'),
    emptyTitle: 'Aún no hay reparto.',
    emptyText: 'Los personajes que entrenes aparecerán aquí.',
    use: 'Usar →',
    copyId: 'Copiar ID',
    forget: 'Quitar de la lista',
    errors: { name: 'Ponle un nombre al personaje.', photos: 'Sube al menos una foto (mejor 10–20 variadas).' },
    status: { not_ready: 'Preparando', queued: 'En cola', in_progress: 'Entrenando', completed: 'Listo', failed: 'Falló' },
    steps: ['Nombre y versión', 'Fotos', 'Entrenar'],
    stepsLabel: 'Pasos para crear tu avatar',
    photoMeter: (n) => (n >= 10 ? `${n} fotos · ¡perfecto!` : `${n} de 10 fotos recomendadas`),
    makeDefault: 'Hacer principal',
    isDefault: 'Principal',
    defaultHint: 'Tu avatar principal se aplica solo en los modelos SOUL de su versión.',
    defaultSet: (name) => `${name} es ahora tu avatar principal.`,
    unsetDefault: 'Quitar como principal',
    training: 'Entrenando tu avatar… suele tardar unos minutos.',
    trained: (name) => `${name} está listo.`,
  },

  settings: {
    title: 'Ajustes',
    close: 'Cerrar',
    mode: 'Modo',
    modeDemo: 'Demostración (sin gastar créditos)',
    modeReal: 'Higgsfield real',
    serverKeys: 'Credenciales del servidor',
    configured: 'Configuradas',
    notConfigured: 'No configuradas',
    studioPassword: 'Contraseña del estudio',
    studioPasswordHint: 'Protege los créditos de la cuenta configurada en el servidor.',
    ownKey: (optional) => `Tu clave de Higgsfield${optional ? ' (opcional)' : ''}`,
    show: 'mostrar',
    hide: 'ocultar',
    keyFormat: 'Formato: KEY_ID:KEY_SECRET (separados por dos puntos).',
    keyHint: ['Créala en', 'Se guarda solo en este navegador y viaja a tu propio servidor, que la reenvía a Higgsfield. Si la dejas vacía se usan las credenciales del servidor.'],
    clear: 'Borrar',
    save: 'Guardar',
    saved: 'Ajustes guardados.',
  },

  prompts: {
    pageTitle: 'Biblioteca de prompts',
    sheetTitle: 'Inspiración',
    imageSource: (n) => `${n} prompts de imagen de la comunidad MeiGen`,
    ownSource: (n, family) => `${n} prompts originales de EDAVI${family ? ` · ${family}` : ''}`,
    surprise: 'Sorpréndeme',
    close: 'Cerrar',
    kinds: { image: 'Imagen', video: 'Video', transform: 'Transformar' },
    search: 'Buscar: retrato, producto, neón, anime…',
    searchLabel: 'Buscar prompts',
    all: 'Todos',
    templatesOnly: 'Solo plantillas',
    bestFor: (family) => `Ideales para ${family}`,
    loading: 'Cargando prompts…',
    none: 'Nada coincide con tu búsqueda.',
    use: 'Usar',
    useIn: (kind) => `Usar en ${kind}`,
    more: (n) => `Ver más (${n} restantes)`,
    shots: (n) => `${n} tomas`,
    template: 'Plantilla',
    recommended: 'Ideal para este modelo',
    seeExample: 'Ver ejemplo ↗',
    credit: ['Prompts de imagen de', '(MIT), creados por sus autores; cada tarjeta enlaza a la publicación original.'],
    applied: 'Prompt aplicado.',
  },

  avatar: {
    alt: 'EDAVI, la mascota del estudio',
    moods: {
      idle: '¿Qué creamos hoy?',
      thinking: 'Generando… esto puede tardar un poco.',
      success: '¡Listo! Mira tu resultado.',
      error: 'Algo salió mal. Revisa el mensaje y reintenta.',
      empty: 'Todavía no hay nada aquí.',
      offline: 'Estoy sin conexión.',
    },
  },

  toasts: {
    sent: (n) => (n > 1 ? `${n} generaciones enviadas.` : 'Generación enviada.'),
    done: (family) => `${family}: resultado listo.`,
    failed: (family) => `${family}: la generación falló.`,
    saved: 'Guardado en tu nube.',
    removed: (n) => `${plural(n, 'creación eliminada', 'creaciones eliminadas')}.`,
    copied: 'Copiado.',
    dismiss: 'Cerrar aviso',
    region: 'Avisos',
    view: 'Ver',
  },

  status: {
    local_queue: 'En cola local', submitting: 'Enviando', queued: 'En cola', in_progress: 'Generando',
    completed: 'Listo', failed: 'Falló', nsfw: 'Bloqueado por moderación', canceled: 'Cancelado', error: 'Error',
  },

  errors: {
    unknown: 'Error desconocido.',
    login: 'Inicia sesión para generar.',
    password: 'Contraseña del estudio incorrecta. Revísala en Ajustes.',
    noCredentials: 'Falta tu clave de Higgsfield. Añádela en Ajustes.',
    badCredentials: 'Credenciales de Higgsfield no válidas. Revisa KEY_ID:KEY_SECRET en Ajustes.',
    private: 'Esta app es privada por ahora. Pide acceso al administrador.',
    credits: 'No tienes créditos suficientes en Higgsfield. Recarga en console.higgsfield.ai.',
    notFound: 'Este modelo no está disponible para tu cuenta (o la solicitud no existe).',
    tooLarge: 'El archivo es demasiado grande.',
    rejected: (detail) => `Parámetros rechazados por el modelo: ${detail}`,
    locked: 'El modelo está bloqueado temporalmente. Inténtalo más tarde.',
    disabled: 'El modelo está desactivado o no está listo. Inténtalo más tarde.',
    unreachable: 'No se pudo contactar con Higgsfield.',
    concurrency: 'Llegaste al máximo de generaciones simultáneas. Se enviará en cuanto termine otra.',
    server: 'Error del servidor de Higgsfield. Reintenta en unos segundos.',
    nsfw: 'La entrada o el resultado fue rechazado por moderación.',
    closedWhileSending: 'La página se cerró mientras se enviaba. Revisa tu consola de Higgsfield.',
  },

  states: {
    errorTitle: 'Algo se rompió',
    errorText: 'Ocurrió un error inesperado. Tu historial está a salvo en este dispositivo.',
    retry: 'Reintentar',
    notFoundTitle: 'Esta página no existe',
    notFoundText: 'Vuelve al estudio para seguir creando.',
    goHome: 'Ir al estudio',
    loading: 'Cargando el estudio…',
  },
};
