// Descripciones en español de cada familia. Si Higgsfield añade una familia nueva
// y no está aquí, se muestra la descripción original en inglés.
export const FAMILY_ES = {
  'cinema-studio-4': 'Planos de cine con control de cámara, lente, luz, época y paleta, más referencias.',
  genjutsu: 'Transfiere el movimiento de un video o sustituye un objeto dentro de él.',
  'grok-image-2': 'Genera y edita imágenes con hasta diez referencias.',
  'grok-video-1-5': 'Video a partir de texto, imágenes o una referencia de audio.',
  'hailuo-2-3': 'Video desde texto o desde una imagen con Hailuo 2.3 Estándar.',
  'happy-horse-1': 'Video desde texto, una imagen inicial o imágenes de referencia.',
  'happy-horse-1-1': 'Video desde texto, una imagen inicial o imágenes de referencia.',
  'ideogram-4': 'Imágenes con tipografía cuidada, referencia opcional y velocidad de render ajustable.',
  'kling-2-5-turbo': 'Video en variantes Estándar y Pro.',
  'kling-2-6': 'Video desde texto o imagen inicial, con sonido opcional.',
  'kling-2-6-motion-control': 'Aplica el movimiento de un video a tu imagen (Estándar o Pro).',
  'kling-3': 'Video en variantes Estándar, Pro, 4K y Turbo, con varias tomas.',
  'kling-3-motion-control': 'Aplica el movimiento de un video a tu imagen (Estándar o Pro).',
  'kling-o3': 'Crea y edita video con primer/último fotograma y referencias de imagen o video.',
  'kling-omni': 'Crea y edita video con referencias de imagen y video.',
  'ltx-2-5': 'Video desde texto o imagen en variantes Rápida y Pro.',
  'marketing-studio-image': 'Imágenes de campaña y producto, con presets que mejoran el prompt.',
  'minimax-h3': 'Video desde texto, fotogramas o referencias multimodales.',
  'pixverse-v6': 'Video desde texto o imagen con sonido opcional.',
  'qwen-image-3': 'Genera imágenes o edita de una a tres referencias, con razonamiento opcional.',
  'recraft-v4-1': 'Imágenes 1K con paleta RGB y color de fondo.',
  'recraft-v4-1-pro': 'Imágenes 2K con paleta RGB y color de fondo.',
  'recraft-v4-1-utility': 'Gráficos 1K con paleta RGB y color de fondo.',
  'recraft-v4-1-utility-pro': 'Gráficos 2K con paleta RGB y color de fondo.',
  'seedance-2': 'Video desde texto, fotogramas o referencias de imagen, video y audio.',
  'seedance-2-5': 'Genera, edita y extiende video con texto y referencias multimodales.',
  'soul-standard': 'Imágenes con estilos seleccionables e intensidad ajustable.',
  'soul-cinema': 'Fotogramas de inspiración cinematográfica a partir de texto.',
  'soul-2': 'Retratos, moda e imágenes editoriales con los estilos SOUL.',
  'wan-2-6': 'Video desde texto, imágenes o referencias de video.',
  'wan-2-7': 'Video desde texto, fotogramas o referencias multimodales.',
  'wan-3': 'Video desde texto, fotogramas o referencias multimodales, con audio.',
  'wan-3-prime': 'La versión Prime de Wan 3.0: video desde texto, fotogramas o referencias.',
  'z-image-turbo': 'Imágenes rápidas en 1K o 2K con mejora opcional del prompt.',
};
